name: Wakey Wakey Claude
on:
  schedule:
    # run at:
    #  - 05:00 AM every day (+08:00 timezone)
    #  - 10:00 AM every day (+08:00 timezone)
    #  - 15:00 AM every day (+08:00 timezone)
    #  - 20:00 AM every day (+08:00 timezone)
    - cron: "0 2,7,12,21 * * *"
  workflow_dispatch:

jobs:
  wakey-wakey:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install claude-code
        run: curl -fsSL https://claude.ai/install.sh | bash

      - name: Run claude command
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          ANTHROPIC_MODEL: haiku
          DISABLE_PROMPT_CACHING: 0
          PROMPT: "reply hi only"
        run: |
          claude \
            --system-prompt "" \
            --tools "" \
            --setting-sources "" \
            --model $ANTHROPIC_MODEL \
            --print "$PROMPT"